---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    labels:
        app: influx-restore
    name: influx-restore
spec:
    replicas: 1
    selector:
        matchLabels:
            app: influx-restore
    servicename: influx-restore
    template:
        metadata:
            labels:
                app: influx-restore
        spec:
            containers:
              - image: influxdb:2.7
                name: influx-restore
                ports:
                  - containerPort: 8086
                    name: influx-restore
                volumeMounts:
                  - mountPath: /var/lib/influxdb2
                    name: data
                volumeMounts:
                  - mountPath: /tmp/backup
                    name: backup
    volumeClaimTemplates:
      - metadata:
            name: data
        spec:
            storageClassName: zfs-hci
            accessModes:
              - ReadWriteOnce
            resources:
                requests:
                    storage: 10Gi
      - metadata:
            name: backup
        spec:
            storageClassName: zfs-hci
            accessModes:
              - ReadWriteOnce
            resources:
                requests:
                    storage: 10Gi                    