---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    labels:
        app: influxdb
    name: influxdb
spec:
    replicas: 1
    selector:
        matchLabels:
            app: influxdb
    serviceName: influxdb
    template:
        metadata:
            labels:
                app: influxdb
        spec:
            hostUsers: false
            securityContext:
              runAsUser: 0
              runAsGroup: 1007
              fsGroup: 1007   
            initContainers:
            - name: fix-permissions
              image: busybox:latest
              command: ["sh", "-c", "chown -R 1007:1007 /var/lib/influxdb2 /tmp/backup"]
              securityContext:
                runAsUser: 0
              volumeMounts:
                - mountPath: /var/lib/influxdb2
                  name: data
                - mountPath: /tmp/backup
                  name: backup                   
            containers:
              - image: influxdb:2.7
                name: influxdb
                ports:
                  - containerPort: 8086
                    name: influxdb
                volumeMounts:
                  - mountPath: /var/lib/influxdb2
                    name: data
                  - mountPath: /tmp/backup
                    name: backup
    volumeClaimTemplates:
      - metadata:
            name: data
        spec:
            storageClassName: zfs-hci
            accessModes:
              - ReadWriteOnce
            resources:
                requests:
                    storage: 10Gi
      - metadata:
            name: backup
        spec:
            storageClassName: zfs-hci
            accessModes:
              - ReadWriteOnce
            resources:
                requests:
                    storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
    name: influxdb
spec:
    ports:
      - name: influxdb
        port: 8086
        targetPort: 8086
    selector:
        app: influxdb
    type: LoadBalancer
    loadBalancerIP: 192.168.179.7