---
- set_fact: paperless_pw="{{ lookup('env', 'paperless_pw') }}"
- name: Copy Deployment file
  copy:
    src: templates/pngx.yml
    dest: pngx.yml

- name: Copy Deployment file
  copy:
    src: templates/gotenberg.yml
    dest: gotenberg.yml

- name: Copy Deployment file
  copy:
    src: templates/tika.yml
    dest: tika.yml       

- name: Copy Deployment file
  copy:
    src: templates/postgres.yml
    dest: postgres.yml     

- name: Set paperless-ngx pw
  replace:
     path: pngx.yml
     regexp: '<<PAPERLESS_PW>>'
     replace: '{{ paperless_pw }}'
  register: paperless_pw

- name: Create a Deployment by reading the definition from a local file
  shell: kubectl apply -f tika.yml >> tika_setup.log
  args:
   creates: tika_setup.log

- name: Create a Deployment by reading the definition from a local file
  shell: kubectl apply -f gotenberg.yml >> gotenberg_setup.log
  args:
   creates: gotenberg_setup.log   

- name: Create a Deployment by reading the definition from a local file
  shell: kubectl apply -f postgres.yml >> postgres_setup.log
  args:
   creates: postgres_setup.log   

- name: Create a Deployment by reading the definition from a local file
  shell: kubectl apply -f pngx.yml >> pngx_setup.log
  args:
   creates: pngx_setup.log