---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp
  labels:
    app: sftp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sftp
  template:
    metadata:
      labels:
        app: sftp
    spec:
      containers:
        - name: sftp
          image: markusmcnugen/sftp
          imagePullPolicy: IfNotPresent
          name: sftp
          args: ["scanner::1001:100:upload"]
          ports:
            - containerPort: 22
              name: sftp
          volumeMounts:
            - name: sftp-data
              mountPath: /home/scanner/upload
            - name: sftp-config    
              mountPath: /config
      volumes:
        - name: sftp-data
          persistentVolumeClaim:
            claimName: sftp-data
        - name: sftp-config
          persistentVolumeClaim:
            claimName: sftp-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftp-data
  labels:
    app: sftp
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftp-config
  labels:
    app: sftp
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi      
---
apiVersion: v1
kind: Service
metadata:
    name: sftp
spec:
    ports:
      - name: sftp
        port: 22
        targetPort: 22
    selector:
        app: sftp
    type: LoadBalancer