---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp
  labels:
    app: sftp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sftp
  template:
    metadata:
      labels:
        app: sftp
    spec:
      hostUsers: false
      securityContext:
        runAsUser: 0
        runAsGroup: 1011
        fsGroup: 1011
      initContainers:
        - name: fix-permissions
          image: busybox:latest
          command: ["sh", "-c", "chown -R :1011 /home/scanner/upload /config"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: sftp-data
              mountPath: /home/scanner/upload
            - name: sftp-config    
              mountPath: /config    
      containers:
        - name: sftp
          image: markusmcnugen/sftp
          imagePullPolicy: IfNotPresent
          name: sftp
          args: ["scanner::1001:100:upload"]
          ports:
            - containerPort: 22
              name: sftp
          volumeMounts:
            - name: sftp-data
              mountPath: /home/scanner/upload
            - name: sftp-config    
              mountPath: /config
      volumes:
        - name: sftp-data
          persistentVolumeClaim:
            claimName: sftp-data
        - name: sftp-config
          persistentVolumeClaim:
            claimName: sftp-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftp-data
  labels:
    app: sftp
spec:
  storageClassName: zfs-hci-shared # Use the SC we defined earlier
  accessModes:
    - ReadWriteOnce # This works for multiple pods on one node!
  resources:
    requests:
      storage: 100Gi      
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftp-config
  labels:
    app: sftp
spec:
  storageClassName: zfs-hci
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi      
---
apiVersion: v1
kind: Service
metadata:
    name: sftp
spec:
    ports:
      - name: sftp
        port: 22
        targetPort: 22
    selector:
        app: sftp
    type: LoadBalancer
    loadBalancerIP: 192.168.179.4