apiVersion: v1
kind: Pod
metadata:
    name: mqtt
    labels: 
        name: emqx
        app: emqx

spec:
    containers:
    - image: emqx/emqx
      name: emqx
      ports:
      - name: mqtt
        containerPort: 1883
      - name: mqtt-http
        containerPort: 18083
---
apiVersion: v1
kind: Service
metadata:
    name: emqx
    labels:
      name: emqx
      app: emqx
      
spec:
    selector:
      name: mqtt
    type: NodePort
    ports:
    - name: mqtt
      nodePort: 31883
      port: 1883
      targetPort: 1883
      protocol: TCP
      
    - name: mqtt-http
      nodePort: 30083
      port: 18083
      targetPort: 18083
      protocol: TCP