apiVersion: v1
kind: Pod
metadata:
    name: mqtt
    labels: 
        name: emqx
        app: emqx
spec:
    containers:
    - image: emqx/emqx
      name: emqx
      ports:
      - name: mqtt
        containerPort: 1883
      - name: mqtt-http
        containerPort: 18083
---
apiVersion: v1
kind: Service
metadata:
    name: emqx
    labels:
      name: emqx
      app: emqx
spec:
    selector:
      name: emqx
    type: LoadBalancer
    loadBalancerIP: 192.168.179.3
    ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      
    - name: mqtt-http
      port: 18083
      targetPort: 18083