---
- name: Ensure cgroupDriver is systemd
  lineinfile:
    path: /var/lib/kubelet/config.yaml
    regexp: '^cgroupDriver.*'
    line: 'cgroupDriver: systemd'
  register: cgroup_driver

- name: restart service kubelet also issue daemon-reload to pick up config changes
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet
  when: cgroup_driver is changed

#Untaint master, so it will be available as worker node
- name: Untaint master node
  shell: kubectl taint nodes --all node-role.kubernetes.io/control-plane- node-role.kubernetes.io/master- >> taint.log
  args:
    chdir: $HOME
    creates: taint.log

- name: Get kube.config
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config

- name: INCLUDE | install metallb
  include_tasks: metallb.yml

- name: INCLUDE | create NFS share
  include_tasks: nfs.yml

- name: Copy Deployment file
  copy:
    src: templates/mdns.yml
    dest: mdns.yml

- name: Create a Deployment by reading the definition from a local file
  shell: kubectl apply -f mdns.yml
