---
- name: Create secret
  shell: kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
  args:
    chdir: $HOME
    creates: metallb_secret.log  

- name: Copy Deployment file
  copy:
    src: templates/metallb.yml
    dest: metallb.yml

- name: Create a Deployment by reading the definition from a local file
  shell: kubectl apply -f metallb.yml >> metallb_setup.log
  args:
   creates: metallb_setup.log