---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    labels:
        app: nodered
    name: nodered
spec:
    replicas: 1
    selector:
        matchLabels:
            app: nodered
    serviceName: nodered
    template:
        metadata:
            labels:
                app: nodered
        spec:
            containers:
              - image: nodered/node-red
                name: nodered
                ports:
                  - containerPort: 1880
                    name: nodered
                volumeMounts:
                  - mountPath: /data
                    name: data
    volumeClaimTemplates:
      - metadata:
            name: data
        spec:
            storageClassName: managed-nfs-storage
            accessModes:
              - ReadWriteOnce
            resources:
                requests:
                    storage: 500M
---
apiVersion: v1
kind: Service
metadata:
    name: nodered
spec:
    ports:
      - name: nodered
        port: 1880
        targetPort: 1880
    selector:
        app: nodered
    type: LoadBalancer
    loadBalancerIP: 192.168.179.6