---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  labels:
    app: paperless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless
  template:
    metadata:
      labels:
        app: paperless
    spec:
      volumes:
        - name: paperless-data
          persistentVolumeClaim:
            claimName: paperless-data
        - name: paperless-media
          persistentVolumeClaim:
            claimName: paperless-media
        - name: paperless-consume
          persistentVolumeClaim:
            claimName: sftp-data
      hostUsers: false
      securityContext:
        runAsUser: 0
        runAsGroup: 1011
        fsGroup: 1011
      initContainers:
        - name: fix-permissions
          image: busybox:latest
          command: ["sh", "-c", "chown -R :1011 /data"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: "/data/data"
              name: paperless-data
            - mountPath: "/data/media"
              name: paperless-media
            - mountPath: "/data/consume"
              name: paperless-consume                 
      containers:      
        - name: paperless
          image: ghcr.io/paperless-ngx/paperless-ngx:latest
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/data/data"
              name: paperless-data
            - mountPath: "/data/media"
              name: paperless-media
            - mountPath: "/data/consume"
              name: paperless-consume
          env:
            - name: PAPERLESS_REDIS
              value: "redis://redis:6379"
            - name: PAPERLESS_DATA_DIR
              value: "/data/data"
            - name: PAPERLESS_MEDIA_ROOT
              value: "/data/media"
            - name: PAPERLESS_CONSUMPTION_DIR
              value: "/data/consume"
            - name: PAPERLESS_ADMIN_USER
              value: "root"
            - name: PAPERLESS_ADMIN_PASSWORD
              value: "<<PAPERLESS_PW>>"
            - name: PAPERLESS_BIND_ADDR
              value: "0.0.0.0"
            - name: PAPERLESS_PORT
              value: "8000"
            - name: PAPERLESS_TIKA_ENABLED
              value: "1"
            - name: PAPERLESS_TIKA_GOTENBERG_ENDPOINT
              value: "http://gotenberg:3000"
            - name: PAPERLESS_TIKA_ENDPOINT
              value: "http://tika:9998"
            - name: PAPERLESS_CONSUMER_ENABLE_BARCODES
              value: "true"
            - name: PAPERLESS_CONSUMER_BARCODE_TIFF_SUPPORT
              value: "true"
            - name: PAPERLESS_DBHOST
              value: "postgres"
            - name: PAPERLESS_FILENAME_FORMAT_REMOVE_NONE
              value: "true"
            - name: PAPERLESS_FILENAME_FORMAT
              value: "{{ created_year }}/{{ created_month }}_{{ created_month_name_short }}/{{ correspondent }}/{{ title }}"
            - name: PAPERLESS_TIME_ZONE
              value: "Europe/Berlin"
            - name: PAPERLESS_TASK_WORKERS
              value: "3"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data
  labels:
    app: paperless
spec:
  storageClassName: zfs-hci
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      hostUsers: false
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-media
  labels:
    app: paperless
spec:
  storageClassName: zfs-hci
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: paperless
spec:
  ports:
    - name: paperless
      port: 80
      targetPort: 8000
  selector:
    app: paperless
  type: LoadBalancer
  loadBalancerIP: 192.168.179.11