---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika
  labels:
    app: tika
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tika
  template:
    metadata:
      labels:
        app: tika
    spec:
      securityContext:
        - readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          privileged: false
          runAsUser: 1001
      containers:
        - name: tika
          image: docker.io/apache/tika:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9998
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: tika
  labels:
    app: tika
spec:
  type: ClusterIP
  ports:
    - port: 9998
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: tika