---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
        - name: home-assistant
          imagePullPolicy: Always
          image: ghcr.io/home-assistant/home-assistant:stable
          ports:
            - containerPort: 8123
            - containerPort: 1400 #sonos
            - containerPort: 21064 #home assistant
          volumeMounts:
            - name: home-assistant-storage
              mountPath: /config
          env:
            - name: TZ
              value: Europe/London

      volumes:
        - name: home-assistant-storage
          persistentVolumeClaim:
            claimName: home-assistant-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-data
  labels:
    app: home-assistant
spec:
  storageClassName: zfs-hci
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
spec:
  ports:
    - name: home-assistant
      port: 80
      targetPort: 8123
    - name: home-assistant-sonos
      port: 1400
      targetPort: 1400
    - name: home-assistant-
      port: 21064
      targetPort: 21064      
  selector:
    app: home-assistant
  type: LoadBalancer
  loadBalancerIP: 192.168.179.10