---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    labels:
        app: iobroker
    name: iobroker
spec:
    replicas: 1
    selector:
        matchLabels:
            app: iobroker
    serviceName: iobroker
    template:
        metadata:
            labels:
                app: iobroker
        spec:
            hostUsers: false
            securityContext:
              runAsUser: 0
              runAsGroup: 1008
              fsGroup: 1008
            initContainers:
             - name: fix-permissions
               image: busybox:latest
               command: ["sh", "-c", "chown -R 1008:1008 /opt/iobroker"]
               securityContext:
                 runAsUser: 0
               volumeMounts:
                - mountPath: /opt/iobroker
                  name: data          
            containers:
              - image: buanet/iobroker:latest-v10
                name: iobroker
                ports:
                  - containerPort: 8081
                    name: iobroker
                volumeMounts:
                  - mountPath: /opt/iobroker
                    name: data
    volumeClaimTemplates:
      - metadata:
            name: data
        spec:
            storageClassName: zfs-hci
            accessModes:
              - ReadWriteOnce
            resources:
                requests:
                    storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
    name: iobroker
spec:
    ports:
      - name: iobroker
        port: 80
        targetPort: 8081
    selector:
        app: iobroker
    type: LoadBalancer
    loadBalancerIP: 192.168.179.8