---
#- name: restart machine
#  shell: reboot
#  async: 1
#  poll: 0
#  ignore_errors: true
#  when: dtoverlay.changed

- name: Install git
  package:
    name: "git-core"
    state: latest

- name: Checkout RPi_Utils
  git:
    repo: https://github.com/ninjablocks/433Utils.git
    dest: /home/pi/433Utils

- name: Build RPi_Util
  make:
    chdir: /home/pi/433Utils/RPi_utils
    target: all

- name: Install python-w1thermsensor, python-pip module
  package:
    name: "python-pip"
    state: latest

- name: Install paho-mqtt
  pip: 
    name: "paho-mqtt"

- name: Copy sensor script
  copy:
    src: default/rf_mqtt.py
    dest: rf_mqtt.py

- name: install rf_mqtt.service systemd unit file
  template: 
    src: default/rf_mqtt.j2 
    dest: /lib/systemd/system/rf_mqtt.service

- name: Create a symbolic link
  file:
    src: /lib/systemd/system/rf_mqtt.service
    dest: /etc/systemd/system/rf_mqtt.service
    state: link
    mode: '0644'

- name: start rf_mqtt service
  systemd: 
    state: started 
    name: rf_mqtt 
    enabled: yes
    masked: no
    daemon_reload: yes