---
- name: Install git
  package:
    name: "git-core"
    state: latest

- name: Checkout RPi_Utils
  git:
    repo: https://github.com/ninjablocks/433Utils.git
    dest: /home/pi/433Utils

- name: Build RPi_Util
  make:
    chdir: /home/pi/433Utils/RPi_utils
    target: all